export type CountyInfo = {
  name: string;
  code: number;
  deliveryTime: string;
  towns: string[];
};

export const KENYA_COUNTIES: CountyInfo[] = [
  {
    name: "Nairobi",
    code: 47,
    deliveryTime: "Same Day / Within 24h",
    towns: [
      "CBD",
      "Westlands",
      "Kilimani",
      "Kileleshwa",
      "Lavington",
      "Karen",
      "Runda",
      "Parklands",
      "South B",
      "South C",
      "Eastleigh",
      "Lang'ata",
      "Ngara",
      "Embakasi",
      "Kasarani",
      "Roysambu",
      "Kahawa West",
      "Gigiri",
      "Upper Hill",
      "Hurlingham",
    ],
  },
  {
    name: "Kiambu",
    code: 22,
    deliveryTime: "Within 24 Hours",
    towns: ["Thika", "Ruiru", "Kikuyu", "Kiambu Town", "Limuru", "Juja", "Karuri", "Githunguri"],
  },
  {
    name: "Mombasa",
    code: 1,
    deliveryTime: "1–2 Business Days",
    towns: ["Mombasa Island", "Nyali", "Bamburi", "Kisauni", "Likoni", "Changamwe", "Mtwapa"],
  },
  {
    name: "Nakuru",
    code: 32,
    deliveryTime: "1–2 Business Days",
    towns: ["Nakuru City", "Naivasha", "Gilgil", "Molo", "Njoro", "Subukia", "Rongai"],
  },
  {
    name: "Kisumu",
    code: 42,
    deliveryTime: "1–2 Business Days",
    towns: ["Kisumu Central", "Milimani", "Kondele", "Maseno", "Ahero", "Muhoroni"],
  },
  {
    name: "Uasin Gishu",
    code: 27,
    deliveryTime: "1–2 Business Days",
    towns: ["Eldoret", "Turbo", "Burnt Forest", "Moiben", "Kesses"],
  },
  {
    name: "Machakos",
    code: 16,
    deliveryTime: "1–2 Business Days",
    towns: ["Machakos Town", "Athi River (Mlolongo/Syokimau)", "Kangundo", "Matungulu", "Tala"],
  },
  {
    name: "Kajiado",
    code: 34,
    deliveryTime: "1–2 Business Days",
    towns: ["Ongata Rongai", "Kitengela", "Ngong", "Kajiado Town", "Loitokitok"],
  },
  {
    name: "Kilifi",
    code: 3,
    deliveryTime: "2–3 Business Days",
    towns: ["Kilifi Town", "Malindi", "Watamu", "Mariakani", "Mtwapa", "Kaloleni"],
  },
  {
    name: "Nyeri",
    code: 19,
    deliveryTime: "1–2 Business Days",
    towns: ["Nyeri Town", "Karatina", "Othaya", "Mukurweini", "Tetu"],
  },
  {
    name: "Meru",
    code: 12,
    deliveryTime: "1–2 Business Days",
    towns: ["Meru Town", "Maua", "Nkubu", "Timau"],
  },
  {
    name: "Laikipia",
    code: 31,
    deliveryTime: "1–2 Business Days",
    towns: ["Nanyuki", "Nyahururu", "Rumuruti", "Doldol"],
  },
  {
    name: "Embu",
    code: 14,
    deliveryTime: "1–2 Business Days",
    towns: ["Embu Town", "Runyenjes", "Siakago"],
  },
  {
    name: "Kirinyaga",
    code: 20,
    deliveryTime: "1–2 Business Days",
    towns: ["Kerugoya", "Kutus", "Sagana", "Baricho", "Wang'uru"],
  },
  {
    name: "Murang'a",
    code: 21,
    deliveryTime: "1–2 Business Days",
    towns: ["Murang'a Town", "Kenol", "Kangema", "Maragua", "Kigumo"],
  },
  {
    name: "Baringo",
    code: 30,
    deliveryTime: "2–3 Business Days",
    towns: ["Kabarnet", "Eldama Ravine", "Marigat", "Mogotio"],
  },
  {
    name: "Bomet",
    code: 36,
    deliveryTime: "2–3 Business Days",
    towns: ["Bomet Town", "Sotik", "Longisa", "Silibwet"],
  },
  {
    name: "Bungoma",
    code: 39,
    deliveryTime: "2–3 Business Days",
    towns: ["Bungoma Town", "Webuye", "Kimilili", "Sirisia", "Chwele"],
  },
  {
    name: "Busia",
    code: 40,
    deliveryTime: "2–3 Business Days",
    towns: ["Busia Town", "Malaba", "Nambale", "Port Victoria"],
  },
  {
    name: "Elgeyo-Marakwet",
    code: 28,
    deliveryTime: "2–3 Business Days",
    towns: ["Iten", "Kapsowar", "Chepkorio"],
  },
  {
    name: "Garissa",
    code: 7,
    deliveryTime: "2–3 Business Days",
    towns: ["Garissa Town", "Dadaab", "Masalani", "Modogashe"],
  },
  {
    name: "Homa Bay",
    code: 43,
    deliveryTime: "2–3 Business Days",
    towns: ["Homa Bay Town", "Mbita", "Oyugis", "Ndhiwa", "Kendu Bay"],
  },
  {
    name: "Isiolo",
    code: 11,
    deliveryTime: "2–3 Business Days",
    towns: ["Isiolo Town", "Garbatulla", "Merti"],
  },
  {
    name: "Kakamega",
    code: 37,
    deliveryTime: "1–2 Business Days",
    towns: ["Kakamega Town", "Mumias", "Malava", "Lugari", "Butere"],
  },
  {
    name: "Kericho",
    code: 35,
    deliveryTime: "1–2 Business Days",
    towns: ["Kericho Town", "Litein", "Kipkelion", "Londiani"],
  },
  {
    name: "Kisii",
    code: 45,
    deliveryTime: "1–2 Business Days",
    towns: ["Kisii Town", "Ogembo", "Suneka", "Nyamache", "Keroka"],
  },
  {
    name: "Kitui",
    code: 15,
    deliveryTime: "2–3 Business Days",
    towns: ["Kitui Town", "Mwingi", "Mutomo", "Kwa Vonza"],
  },
  {
    name: "Kwale",
    code: 2,
    deliveryTime: "2–3 Business Days",
    towns: ["Diani", "Ukunda", "Kwale Town", "Msambweni", "Lunga Lunga"],
  },
  {
    name: "Lamu",
    code: 5,
    deliveryTime: "2–4 Business Days",
    towns: ["Lamu Island", "Mpeketoni", "Shela", "Witu"],
  },
  {
    name: "Makueni",
    code: 17,
    deliveryTime: "1–2 Business Days",
    towns: ["Wote", "Makindu", "Emali", "Mtito Andei", "Kibwezi"],
  },
  {
    name: "Mandera",
    code: 9,
    deliveryTime: "3–4 Business Days",
    towns: ["Mandera Town", "Rhamu", "Elwak"],
  },
  {
    name: "Marsabit",
    code: 10,
    deliveryTime: "3–4 Business Days",
    towns: ["Marsabit Town", "Moyale", "Laisamis", "North Horr"],
  },
  {
    name: "Migori",
    code: 44,
    deliveryTime: "2–3 Business Days",
    towns: ["Migori Town", "Isebania", "Rongo", "Kehancha", "Awendo"],
  },
  {
    name: "Nandi",
    code: 29,
    deliveryTime: "2–3 Business Days",
    towns: ["Kapsabet", "Nandi Hills", "Mosoriot", "Kobujoi"],
  },
  {
    name: "Narok",
    code: 33,
    deliveryTime: "2–3 Business Days",
    towns: ["Narok Town", "Kilgoris", "Ololulung'a", "Suswa"],
  },
  {
    name: "Nyamira",
    code: 46,
    deliveryTime: "2–3 Business Days",
    towns: ["Nyamira Town", "Nyansiongo", "Keroka", "Manga"],
  },
  {
    name: "Nyandarua",
    code: 18,
    deliveryTime: "1–2 Business Days",
    towns: ["Ol Kalou", "Engineer", "Ndaragwa", "Mairo Inya"],
  },
  {
    name: "Samburu",
    code: 25,
    deliveryTime: "2–3 Business Days",
    towns: ["Maralal", "Baragoi", "Archers Post", "Wamba"],
  },
  {
    name: "Siaya",
    code: 41,
    deliveryTime: "2–3 Business Days",
    towns: ["Siaya Town", "Bondo", "Ugunja", "Yala", "Usenge"],
  },
  {
    name: "Taita-Taveta",
    code: 6,
    deliveryTime: "2–3 Business Days",
    towns: ["Voi", "Wundanyi", "Taveta", "Mwatate"],
  },
  {
    name: "Tana River",
    code: 4,
    deliveryTime: "2–4 Business Days",
    towns: ["Hola", "Garsen", "Bura", "Madogo"],
  },
  {
    name: "Tharaka-Nithi",
    code: 13,
    deliveryTime: "2–3 Business Days",
    towns: ["Chuka", "Marimanti", "Kathwana"],
  },
  {
    name: "Trans Nzoia",
    code: 26,
    deliveryTime: "2–3 Business Days",
    towns: ["Kitale", "Endebess", "Kiminini"],
  },
  {
    name: "Turkana",
    code: 23,
    deliveryTime: "3–4 Business Days",
    towns: ["Lodwar", "Kakuma", "Lokichogio", "Kalokol"],
  },
  {
    name: "Vihiga",
    code: 38,
    deliveryTime: "2–3 Business Days",
    towns: ["Mbale", "Chavakali", "Luanda", "Hamisi"],
  },
  {
    name: "Wajir",
    code: 8,
    deliveryTime: "3–4 Business Days",
    towns: ["Wajir Town", "Habaswein", "Bute", "Eldas"],
  },
  {
    name: "West Pokot",
    code: 24,
    deliveryTime: "3–4 Business Days",
    towns: ["Kapenguria", "Makutano", "Chepareria", "Ortum"],
  },
];

export function findCounty(countyName: string): CountyInfo | undefined {
  return KENYA_COUNTIES.find((c) => c.name.toLowerCase() === countyName.trim().toLowerCase());
}
