export const categories = [
  { id: '1', name: 'Hoodies', slug: 'hoodies', image_url: null, description: null, sort_order: 1, created_at: '' },
  { id: '2', name: 'T-Shirts', slug: 't-shirts', image_url: null, description: null, sort_order: 2, created_at: '' },
  { id: '3', name: 'Accessories', slug: 'accessories', image_url: null, description: null, sort_order: 3, created_at: '' },
  { id: '4', name: 'Bottoms', slug: 'bottoms', image_url: null, description: null, sort_order: 4, created_at: '' },
  { id: '5', name: 'Outerwear', slug: 'outerwear', image_url: null, description: null, sort_order: 5, created_at: '' },
]

export const products = [
  {
    id: '1',
    name: 'O&N Classic Hoodie',
    slug: 'on-classic-hoodie',
    description: 'The timeless O&N hoodie. Premium cotton fleece with a relaxed fit, perfect for everyday wear.',
    price: 3500,
    sale_price: null,
    category_id: '1',
    is_new_arrival: false,
    is_featured: true,
    is_best_seller: true,
    stock_quantity: 48,
    sku: 'ON-HOOD-001',
    created_at: '2025-01-15T00:00:00Z',
    images: [
      { id: 'img-1-1', product_id: '1', image_url: '/placeholder-hoodie.jpg', alt_text: 'O&N Classic Hoodie front view', sort_order: 0 },
      { id: 'img-1-2', product_id: '1', image_url: '/placeholder-hoodie-2.jpg', alt_text: 'O&N Classic Hoodie back view', sort_order: 1 },
    ],
    variants: [
      { id: 'var-1-xs', product_id: '1', size: 'XS', color: null, sku: 'ON-HOOD-001-XS', stock_quantity: 8, price: 3500, sale_price: null },
      { id: 'var-1-s', product_id: '1', size: 'S', color: null, sku: 'ON-HOOD-001-S', stock_quantity: 10, price: 3500, sale_price: null },
      { id: 'var-1-m', product_id: '1', size: 'M', color: null, sku: 'ON-HOOD-001-M', stock_quantity: 12, price: 3500, sale_price: null },
      { id: 'var-1-l', product_id: '1', size: 'L', color: null, sku: 'ON-HOOD-001-L', stock_quantity: 10, price: 3500, sale_price: null },
      { id: 'var-1-xl', product_id: '1', size: 'XL', color: null, sku: 'ON-HOOD-001-XL', stock_quantity: 8, price: 3500, sale_price: null },
    ],
  },
  {
    id: '2',
    name: 'O&N Minimal Tee',
    slug: 'on-minimal-tee',
    description: 'Clean, minimal and effortless. A wardrobe essential cut from soft organic cotton.',
    price: 2200,
    sale_price: null,
    category_id: '2',
    is_new_arrival: false,
    is_featured: true,
    is_best_seller: true,
    stock_quantity: 60,
    sku: 'ON-TEE-001',
    created_at: '2025-01-20T00:00:00Z',
    images: [
      { id: 'img-2-1', product_id: '2', image_url: '/placeholder-tee.jpg', alt_text: 'O&N Minimal Tee front view', sort_order: 0 },
    ],
    variants: [
      { id: 'var-2-xs', product_id: '2', size: 'XS', color: null, sku: 'ON-TEE-001-XS', stock_quantity: 12, price: 2200, sale_price: null },
      { id: 'var-2-s', product_id: '2', size: 'S', color: null, sku: 'ON-TEE-001-S', stock_quantity: 14, price: 2200, sale_price: null },
      { id: 'var-2-m', product_id: '2', size: 'M', color: null, sku: 'ON-TEE-001-M', stock_quantity: 14, price: 2200, sale_price: null },
      { id: 'var-2-l', product_id: '2', size: 'L', color: null, sku: 'ON-TEE-001-L', stock_quantity: 12, price: 2200, sale_price: null },
      { id: 'var-2-xl', product_id: '2', size: 'XL', color: null, sku: 'ON-TEE-001-XL', stock_quantity: 8, price: 2200, sale_price: null },
    ],
  },
  {
    id: '3',
    name: 'O&N Signature Cap',
    slug: 'on-signature-cap',
    description: 'Structured six-panel cap with embroidered O&N logo. Adjustable strap for a perfect fit.',
    price: 1500,
    sale_price: null,
    category_id: '3',
    is_new_arrival: false,
    is_featured: false,
    is_best_seller: true,
    stock_quantity: 35,
    sku: 'ON-CAP-001',
    created_at: '2025-02-01T00:00:00Z',
    images: [
      { id: 'img-3-1', product_id: '3', image_url: '/placeholder-cap.jpg', alt_text: 'O&N Signature Cap front view', sort_order: 0 },
    ],
    variants: [
      { id: 'var-3-os', product_id: '3', size: 'One Size', color: null, sku: 'ON-CAP-001-OS', stock_quantity: 35, price: 1500, sale_price: null },
    ],
  },
  {
    id: '4',
    name: 'O&N Essential Hoodie',
    slug: 'on-essential-hoodie',
    description: 'The essential layer. Heavyweight cotton with a modern dropped shoulder silhouette.',
    price: 3800,
    sale_price: 3200,
    category_id: '1',
    is_new_arrival: true,
    is_featured: true,
    is_best_seller: false,
    stock_quantity: 40,
    sku: 'ON-HOOD-002',
    created_at: '2025-03-01T00:00:00Z',
    images: [
      { id: 'img-4-1', product_id: '4', image_url: '/placeholder-hoodie-essential.jpg', alt_text: 'O&N Essential Hoodie front view', sort_order: 0 },
      { id: 'img-4-2', product_id: '4', image_url: '/placeholder-hoodie-essential-2.jpg', alt_text: 'O&N Essential Hoodie back view', sort_order: 1 },
    ],
    variants: [
      { id: 'var-4-xs', product_id: '4', size: 'XS', color: null, sku: 'ON-HOOD-002-XS', stock_quantity: 6, price: 3800, sale_price: 3200 },
      { id: 'var-4-s', product_id: '4', size: 'S', color: null, sku: 'ON-HOOD-002-S', stock_quantity: 8, price: 3800, sale_price: 3200 },
      { id: 'var-4-m', product_id: '4', size: 'M', color: null, sku: 'ON-HOOD-002-M', stock_quantity: 10, price: 3800, sale_price: 3200 },
      { id: 'var-4-l', product_id: '4', size: 'L', color: null, sku: 'ON-HOOD-002-L', stock_quantity: 8, price: 3800, sale_price: 3200 },
      { id: 'var-4-xl', product_id: '4', size: 'XL', color: null, sku: 'ON-HOOD-002-XL', stock_quantity: 8, price: 3800, sale_price: 3200 },
    ],
  },
  {
    id: '5',
    name: 'O&N Overshirt',
    slug: 'on-overshirt',
    description: 'A versatile overshirt in a relaxed fit. Built from durable twill with a clean, structured look.',
    price: 3200,
    sale_price: null,
    category_id: '5',
    is_new_arrival: false,
    is_featured: true,
    is_best_seller: false,
    stock_quantity: 22,
    sku: 'ON-OVER-001',
    created_at: '2025-02-10T00:00:00Z',
    images: [
      { id: 'img-5-1', product_id: '5', image_url: '/placeholder-overshirt.jpg', alt_text: 'O&N Overshirt front view', sort_order: 0 },
    ],
    variants: [
      { id: 'var-5-s', product_id: '5', size: 'S', color: null, sku: 'ON-OVER-001-S', stock_quantity: 6, price: 3200, sale_price: null },
      { id: 'var-5-m', product_id: '5', size: 'M', color: null, sku: 'ON-OVER-001-M', stock_quantity: 8, price: 3200, sale_price: null },
      { id: 'var-5-l', product_id: '5', size: 'L', color: null, sku: 'ON-OVER-001-L', stock_quantity: 5, price: 3200, sale_price: null },
      { id: 'var-5-xl', product_id: '5', size: 'XL', color: null, sku: 'ON-OVER-001-XL', stock_quantity: 3, price: 3200, sale_price: null },
    ],
  },
  {
    id: '6',
    name: 'O&N Slim Trousers',
    slug: 'on-slim-trousers',
    description: 'Tapered slim trousers in stretch cotton. A sharp everyday pant with just the right amount of structure.',
    price: 2800,
    sale_price: null,
    category_id: '4',
    is_new_arrival: false,
    is_featured: false,
    is_best_seller: true,
    stock_quantity: 30,
    sku: 'ON-PANT-001',
    created_at: '2025-01-25T00:00:00Z',
    images: [
      { id: 'img-6-1', product_id: '6', image_url: '/placeholder-trousers.jpg', alt_text: 'O&N Slim Trousers front view', sort_order: 0 },
    ],
    variants: [
      { id: 'var-6-s', product_id: '6', size: 'S', color: null, sku: 'ON-PANT-001-S', stock_quantity: 6, price: 2800, sale_price: null },
      { id: 'var-6-m', product_id: '6', size: 'M', color: null, sku: 'ON-PANT-001-M', stock_quantity: 8, price: 2800, sale_price: null },
      { id: 'var-6-l', product_id: '6', size: 'L', color: null, sku: 'ON-PANT-001-L', stock_quantity: 8, price: 2800, sale_price: null },
      { id: 'var-6-xl', product_id: '6', size: 'XL', color: null, sku: 'ON-PANT-001-XL', stock_quantity: 8, price: 2800, sale_price: null },
    ],
  },
  {
    id: '7',
    name: 'O&N Crewneck',
    slug: 'on-crewneck',
    description: 'A classic crewneck sweatshirt in heavyweight brushed fleece. Ribbed cuffs and hem for a clean finish.',
    price: 3000,
    sale_price: null,
    category_id: '1',
    is_new_arrival: true,
    is_featured: false,
    is_best_seller: false,
    stock_quantity: 36,
    sku: 'ON-HOOD-003',
    created_at: '2025-03-10T00:00:00Z',
    images: [
      { id: 'img-7-1', product_id: '7', image_url: '/placeholder-crewneck.jpg', alt_text: 'O&N Crewneck front view', sort_order: 0 },
      { id: 'img-7-2', product_id: '7', image_url: '/placeholder-crewneck-2.jpg', alt_text: 'O&N Crewneck detail view', sort_order: 1 },
    ],
    variants: [
      { id: 'var-7-xs', product_id: '7', size: 'XS', color: null, sku: 'ON-HOOD-003-XS', stock_quantity: 6, price: 3000, sale_price: null },
      { id: 'var-7-s', product_id: '7', size: 'S', color: null, sku: 'ON-HOOD-003-S', stock_quantity: 8, price: 3000, sale_price: null },
      { id: 'var-7-m', product_id: '7', size: 'M', color: null, sku: 'ON-HOOD-003-M', stock_quantity: 8, price: 3000, sale_price: null },
      { id: 'var-7-l', product_id: '7', size: 'L', color: null, sku: 'ON-HOOD-003-L', stock_quantity: 7, price: 3000, sale_price: null },
      { id: 'var-7-xl', product_id: '7', size: 'XL', color: null, sku: 'ON-HOOD-003-XL', stock_quantity: 7, price: 3000, sale_price: null },
    ],
  },
  {
    id: '8',
    name: 'O&N Cargo Pants',
    slug: 'on-cargo-pants',
    description: 'Relaxed cargo pants with side pockets and a tapered leg. Made from durable cotton canvas.',
    price: 2600,
    sale_price: null,
    category_id: '4',
    is_new_arrival: false,
    is_featured: false,
    is_best_seller: false,
    stock_quantity: 25,
    sku: 'ON-PANT-002',
    created_at: '2025-02-20T00:00:00Z',
    images: [
      { id: 'img-8-1', product_id: '8', image_url: '/placeholder-cargo.jpg', alt_text: 'O&N Cargo Pants front view', sort_order: 0 },
    ],
    variants: [
      { id: 'var-8-s', product_id: '8', size: 'S', color: null, sku: 'ON-PANT-002-S', stock_quantity: 5, price: 2600, sale_price: null },
      { id: 'var-8-m', product_id: '8', size: 'M', color: null, sku: 'ON-PANT-002-M', stock_quantity: 6, price: 2600, sale_price: null },
      { id: 'var-8-l', product_id: '8', size: 'L', color: null, sku: 'ON-PANT-002-L', stock_quantity: 7, price: 2600, sale_price: null },
      { id: 'var-8-xl', product_id: '8', size: 'XL', color: null, sku: 'ON-PANT-002-XL', stock_quantity: 7, price: 2600, sale_price: null },
    ],
  },
  {
    id: '9',
    name: 'O&N Beanie',
    slug: 'on-beanie',
    description: 'A classic ribbed beanie in soft merino wool blend. Keeps you warm without the bulk.',
    price: 1200,
    sale_price: null,
    category_id: '3',
    is_new_arrival: false,
    is_featured: false,
    is_best_seller: false,
    stock_quantity: 50,
    sku: 'ON-ACC-001',
    created_at: '2025-01-05T00:00:00Z',
    images: [
      { id: 'img-9-1', product_id: '9', image_url: '/placeholder-beanie.jpg', alt_text: 'O&N Beanie front view', sort_order: 0 },
    ],
    variants: [
      { id: 'var-9-os', product_id: '9', size: 'One Size', color: null, sku: 'ON-ACC-001-OS', stock_quantity: 50, price: 1200, sale_price: null },
    ],
  },
  {
    id: '10',
    name: 'O&N Jacket',
    slug: 'on-jacket',
    description: 'A sharp tailored jacket in a structured wool blend. Fully lined with interior pockets.',
    price: 4500,
    sale_price: 3800,
    category_id: '5',
    is_new_arrival: true,
    is_featured: true,
    is_best_seller: false,
    stock_quantity: 15,
    sku: 'ON-OUT-001',
    created_at: '2025-03-15T00:00:00Z',
    images: [
      { id: 'img-10-1', product_id: '10', image_url: '/placeholder-jacket.jpg', alt_text: 'O&N Jacket front view', sort_order: 0 },
      { id: 'img-10-2', product_id: '10', image_url: '/placeholder-jacket-2.jpg', alt_text: 'O&N Jacket detail view', sort_order: 1 },
    ],
    variants: [
      { id: 'var-10-s', product_id: '10', size: 'S', color: null, sku: 'ON-OUT-001-S', stock_quantity: 4, price: 4500, sale_price: 3800 },
      { id: 'var-10-m', product_id: '10', size: 'M', color: null, sku: 'ON-OUT-001-M', stock_quantity: 5, price: 4500, sale_price: 3800 },
      { id: 'var-10-l', product_id: '10', size: 'L', color: null, sku: 'ON-OUT-001-L', stock_quantity: 4, price: 4500, sale_price: 3800 },
      { id: 'var-10-xl', product_id: '10', size: 'XL', color: null, sku: 'ON-OUT-001-XL', stock_quantity: 2, price: 4500, sale_price: 3800 },
    ],
  },
  {
    id: '11',
    name: 'O&N Tank Top',
    slug: 'on-tank-top',
    description: 'A slim-fit tank top in lightweight pima cotton. Perfect for layering or worn on its own.',
    price: 1800,
    sale_price: null,
    category_id: '2',
    is_new_arrival: false,
    is_featured: false,
    is_best_seller: false,
    stock_quantity: 42,
    sku: 'ON-TEE-002',
    created_at: '2025-02-05T00:00:00Z',
    images: [
      { id: 'img-11-1', product_id: '11', image_url: '/placeholder-tank.jpg', alt_text: 'O&N Tank Top front view', sort_order: 0 },
    ],
    variants: [
      { id: 'var-11-xs', product_id: '11', size: 'XS', color: null, sku: 'ON-TEE-002-XS', stock_quantity: 8, price: 1800, sale_price: null },
      { id: 'var-11-s', product_id: '11', size: 'S', color: null, sku: 'ON-TEE-002-S', stock_quantity: 9, price: 1800, sale_price: null },
      { id: 'var-11-m', product_id: '11', size: 'M', color: null, sku: 'ON-TEE-002-M', stock_quantity: 9, price: 1800, sale_price: null },
      { id: 'var-11-l', product_id: '11', size: 'L', color: null, sku: 'ON-TEE-002-L', stock_quantity: 8, price: 1800, sale_price: null },
      { id: 'var-11-xl', product_id: '11', size: 'XL', color: null, sku: 'ON-TEE-002-XL', stock_quantity: 8, price: 1800, sale_price: null },
    ],
  },
  {
    id: '12',
    name: 'O&N Shorts',
    slug: 'on-shorts',
    description: 'Everyday shorts in relaxed cotton jersey. Elasticated waistband with an adjustable drawcord.',
    price: 2400,
    sale_price: null,
    category_id: '4',
    is_new_arrival: false,
    is_featured: false,
    is_best_seller: false,
    stock_quantity: 33,
    sku: 'ON-SHORT-001',
    created_at: '2025-02-15T00:00:00Z',
    images: [
      { id: 'img-12-1', product_id: '12', image_url: '/placeholder-shorts.jpg', alt_text: 'O&N Shorts front view', sort_order: 0 },
    ],
    variants: [
      { id: 'var-12-s', product_id: '12', size: 'S', color: null, sku: 'ON-SHORT-001-S', stock_quantity: 7, price: 2400, sale_price: null },
      { id: 'var-12-m', product_id: '12', size: 'M', color: null, sku: 'ON-SHORT-001-M', stock_quantity: 8, price: 2400, sale_price: null },
      { id: 'var-12-l', product_id: '12', size: 'L', color: null, sku: 'ON-SHORT-001-L', stock_quantity: 9, price: 2400, sale_price: null },
      { id: 'var-12-xl', product_id: '12', size: 'XL', color: null, sku: 'ON-SHORT-001-XL', stock_quantity: 9, price: 2400, sale_price: null },
    ],
  },
]

export function getProductBySlug(slug: string) {
  return products.find(p => p.slug === slug) ?? null
}

export function getProductsByCategory(categorySlug: string) {
  const category = categories.find(c => c.slug === categorySlug)
  if (!category) return []
  return products.filter(p => p.category_id === category.id)
}

export function getNewArrivals() {
  return products.filter(p => p.is_new_arrival)
}

export function getFeaturedProducts() {
  return products.filter(p => p.is_featured)
}

export function getBestSellers() {
  return products.filter(p => p.is_best_seller)
}
